name: Build devcontainer
description: build devcontainer based on ./devcontainer/devcontainer.json

inputs:
  username:
    required: true
    type: string
  token:
    required: true
    type: string
  image:
    required: false
    type: string
    default: ghcr.io/hayas1/devcontainer-features/devcontainer
  run:
    required: true
    type: string

runs:
  using: composite
  steps:
    - uses: dtolnay/rust-toolchain@stable
    - name: Install dependencies
      run: cargo install json5-to-json
      shell: bash
    - name: Remove "mounts" spec
      run: |
        cat .devcontainer/devcontainer.json |
          json5-to-json |
          jq '.mounts |= map(select(. | contains("source=${localEnv:HOME}/.config/gh")))' >./tmp.json &&
          mv ./tmp.json .devcontainer/devcontainer.json
      shell: bash
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}
    - name: Build devcontainer
      uses: devcontainers/ci@v0.2
      with:
        imageName: ${{ inputs.image }}
        runCmd: ${{ inputs.run }}