name: Build devcontainer
description: build devcontainer based on ./devcontainer/devcontainer.json

inputs:
  username:
    required: true
    description: Username for github container registry
    type: string
  token:
    required: true
    description: Token for github container registry
    type: string
  image:
    required: false
    description: Image name for built devcontainer
    type: string
    default: ghcr.io/hayas1/devcontainer-features/devcontainer
  testing:
    required: true
    description: run command after build devcontainer for testing
    type: string
  directory:
    required: false
    description: directory that container `.devcontainer` direcotry
    type: string
    default:
  prepare:
    required: false
    description: run command before build devcontainer for preparation

runs:
  using: composite
  steps:
    - name: Prepare (typically, mounts paths)
      run: ${{ inputs.prepare }}
      shell: bash
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}
    - name: Build devcontainer
      uses: devcontainers/ci@v0.2
      with:
        imageName: ${{ inputs.image }}
        runCmd: ${{ inputs.testing }}
        subFolder: ${{ inputs.directory }}