name: Bulid devcontainer
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/devcontainer
        with:
          username: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          run: 'mv "${HOME}/.zshrc" "${HOME}/.zshenv" && zsh .devcontainer/test.sh'