name: Commit generated documentation
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  doc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Validate devcontainer-feature.json and generate document
        uses: devcontainers/action@v1
        with:
          # validate-only: "true"
          base-path-to-features: "./src"
          generate-docs: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Git add and diff
        id: diff
        run: git add '*/**/README.md' && git diff $(git branch --show-current) --name-only --exit-code
        continue-on-error: true
      - name: Git commit and push
        if: steps.diff.outcome == 'failure'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git commit -m 'generated from devcontainer-feature.json'
          git push
