name: Release devcontainer features
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Publish features
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./src"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/devcontainer
        with:
          username: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prepare: bash ./init.sh
          testing: mv "${HOME}/.zshrc" "${HOME}/.zshenv" && zsh .devcontainer/test.sh
  script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check script
        run: |
          curl -fsL 'https://github.com/hayas1/devcontainer-features/raw/main/init.sh' |
            DEVCONTAINER_DIR=./devcontainer bash &&
            diff ./.devcontainer/devcontainer.json ./devcontainer/devcontainer.json &&
            diff ./.devcontainer/entry.sh ./devcontainer/entry.sh